In [ ]:
마방진(가로, 세로, 대각선 방향의 숫자 합계가 모두 같은 배열) 만들기
최초의 '1'이 채워지는 자리는 첫 줄 정 가운대 열 => 홀수차 정방행렬(행과 열의 개수가 같은 행렬)만 가능하다
직전에 채워진 숫자의 값에 따라 다음에 채워질 숫자의 위치가 결정된다
직전에 채워진 숫자가 행렬의 차수(n)의 배수면 다음 숫자는 아래줄에 채운다 => 행 + 1
직전에 채워진 숫자가 n의 배수가 아니면 다음 숫자는 오른쪽 위 방향으로 채운다 => 행 - 1, 열 + 1
행이 0보다 작아지면 행의 위치를 마지막 위치로 변경한 후 채우고 열이 행렬의 차수와 같아지면 열의 위치를 0으로 변경한다

In [8]:
# 1차원 리스트 만들기
a = [0 for i in range(5)] # 0이 5번 반복되는 1차원 리스트
print(a)
# 2차원 리스트 => 리스트 이름 = [[0] * 열의 개수 for 변수 in range(행의 개수)]
b = [[0] * 5 for i in range(5)]
print(b)
import numpy as np
c = np.array(b)
print(c)

[0, 0, 0, 0, 0]
[[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0]]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [9]:
for i in range(5): # 행
    for j in range(5): # 열
        print('{0:2d} '.format(b[i][j]), end='')
    print()

 0  0  0  0  0 
 0  0  0  0  0 
 0  0  0  0  0 
 0  0  0  0  0 
 0  0  0  0  0 


In [6]:
# 5행 5열인 2차원 리스트를 선언한다
a = [[0] * 5 for i in range(5)]
# 5행 5열일 경우 최초의 '1'이 채워질 위치를 정한다
i = 0 # 행
j = 2 # 열


for k in range(1, 26):
    a[i][j] = k
    # 마방진에 채운 숫자가 5의 배수인가 판단한다
    if k % 5 == 0:
        # 5의 배수면 다음에 채워질 숫자의 위치는 행만 1증가시킨다
         i += 1
    else:
        # 5의 배수가 아니면 다음에 채워질 숫자의 위치는 행 1감소, 열 1증가시킨다
        i -= 1
        # 행이 감소하다가 0보다 작아지면 마지막 행으로 행의 위치를 조정한다
        if i < 0:
            i = 4
        j += 1
        # 열이 증가하다 5가 되면 첫 번째 열로 열의 위치를 조정한다
        if j >= 5:
            j = 0
# =====for k in range 

for i in range(5): # 행
    for j in range(5): # 열
        print('{0:2d} '.format(a[i][j]), end='')
    print()

17 24  1  8 15 
23  5  7 14 16 
 4  6 13 20 22 
10 12 19 21  3 
11 18 25  2  9 


In [2]:
# 작성할 마방진의 차수를 3이 상인 홀수로 받는다
while True:
    n = int(input("3이상인 홀수를 입력하세요 : "))
    if n >= 3 and n % 2 == 1:
        break
    print('콱~~~~~~~~~')
    
# n행 n열인 2차원 리스트를 만든다
a = [[0] * n for i in range(n)]
i = 0 
# 행렬의 차수에 따라 최초의 '1'이 채워질 열을 계산한다
j = n // 2 

for k in range(1, n ** 2 + 1):
    a[i][j] = k
    if k % n == 0:
         i += 1
    else:
        i -= 1
        if i < 0:
            i = n - 1
        j += 1
        if j >= n:
            j = 0

for i in range(n): 
    for j in range(n): 
        print('{0:3d} '.format(a[i][j]), end='')
    print()

3이상인 홀수를 입력하세요 : 5
 17  24   1   8  15 
 23   5   7  14  16 
  4   6  13  20  22 
 10  12  19  21   3 
 11  18  25   2   9 
